//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public System.Guid accountId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime createtime { get; set; }
        public Nullable<System.DateTime> lastlogintime { get; set; }
        public bool islogon { get; set; }
        public int empolyeeid { get; set; }
    }
}
